name: Deploy project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependency
        run: npm ci
      - name: Run tests
        run: npm test
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependency
        run: npm ci
      - name: Run linter
        run: npm run lint
  deploy:
    needs: [test, linting]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependency
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploing ..."
